code/kelin/labs/django_labs/lab01_todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

code/kelin/labs/django_labs/lab05_blog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blogapp.urls')),
    path('admin/', admin.site.urls)
]

code/kelin/labs/django_labs/lab05_blog/blog/blogapp/urls.py
# Create the following pages:

# Profile /profile/
# show a list of the user's own posts, only showing the title of each
# Create Post /create/
# form for creating a new post


from django.urls import path
from . import views

app_name = 'blogapp'
urlpatterns = [    
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.loginto, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('create/', views.create, name='create'),
]

code/kelin/labs/django_labs/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

code/kelin/labs/django_labs/lab05_blog/blog/blogapp/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create the following model:

# BlogPost
# title (CharField)
# body (TextField)
# user (ForeignKey to django.contrib.auth.models.User)
# public (BooleanField)
# date_created (DateTimeField with auto_now_add=True)
# date_edited (DateTimeField with auto_now=True)


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    public = models.BooleanField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

code/kelin/labs/django_labs/lab05_blog/blog/blogapp/forms.py
from django import forms
from .models import BlogPost
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','password1','password2')

class BlogForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'
        widgets = {'user': forms.HiddenInput()}

code/kelin/labs/django_labs/lab05_blog/blog/blogapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout, get_user
from django.contrib.auth.forms import AuthenticationForm
from .models import BlogPost
from .forms import BlogForm

# Create the following views:

# Register /register/
# form for creating a new user
# redirect to /profile/ after registering

def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=password)
            login(request, user)
            return redirect('blogapp:profile')
        else:
            return redirect('blogapp:register')    
    form = NewUserForm()
    context = {
        'form':form,
    }

    return render(request,'blog/register.html', context )

# Login /login/
# form for logging a user in
# redirect to /profile/ after logging in
        
def loginto(request):
    if request.method=="POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.data.get('username')
            password = form.data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            if user is not None:
                return redirect('blogapp:profile')
            else:
                return redirect('blogapp:login')
        else:
            return redirect('blogapp:login')
    form = AuthenticationForm()
    return render(request, 'blog/login.html', {'form':form})

# Profile /profile/
# a protected page only logged in users can see
# just show a welcome message for now

def profile(request):
    blog = BlogPost.objects.filter(user=request.user).all()
    context = {
        'message': 'Profile page',
        'blog':blog,
    }
    return render(request, 'blog/profile.html', context)
    pass

def logout_view(request):
    logout(request)
    return redirect('blogapp:login')


def create(request):
    if User.is_authenticated:
        if request.method == 'POST':
            form = BlogForm(request.POST, request.FILES)            
            if form.is_valid():
                form.save()
                return redirect('blogapp:profile')
            else:
                pass
        else:
            person = get_user(request)
            print('Loading user')
            form = BlogForm(initial={'user':person})        

        context = {
            'form':form
        }
        return render(request, 'blog/create.html', context)
    else:
        return redirect('blogapp:login')

code/kelin/labs/django_labs/lab05_blog/blog/blogapp/templates/blog/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
</head>
<body>
    {% if user.is_authenticated %}
    <p>Welcome {{user.username}}</p>
    <p><a href='{% url "blogapp:logout" %}'>Logout</a></p>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_ul}}
        <input type="submit" value="submit">
    </form>
    {% else %}
    <h2>You are not logged in</h2>
    <a href='{% url "blogapp:login" %}'>Login</a>.
    {% endif %}    
</body>
</html>

code/kelin/labs/django_labs/lab05_blog/blog/blogapp/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Please Login</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>
    <h2>New User?</h2>
    <p><a href="{% url 'blogapp:register' %}">Register</a></p>
</body>
</html>

code/kelin/labs/django_labs/lab05_blog/blog/blogapp/templates/blog/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    <div>{{message}}</div>
    
    <ul>
        {% for blogs in blog %}
        <li>{{ blogs.title }}</li>
        {% endfor %}
    </ul>
    {% if user.is_authenticated %}
    <div> Hello {{user.username}}</div>
    <p><a href="{% url 'blogapp:logout' %}">Logout</a></p>
    {% else %}
    <div>You are not logged in</div>
    <p><a href="{% url 'blogapp:login' %}">Login</a></p>
    {% endif %}
    <div>{{form}}</div>
    <p><a href="{% url 'blogapp:create' %}">Create New Blog</a></p>
    
</body>
</html>

code/kelin/labs/django_labs/lab05_blog/blog/blogapp/templates/blog/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Register</button>
    </form>
    {% if user.is_authenticated %}
    <div> Hello {{user.username}}</div>
    <p><a href="{% url 'blogapp:logout' %}">Logout</a></p>
    {% else %}<br>
    <h2>Already registered?</h2>
    <p><a href="{% url 'blogapp:login' %}">Login</a></p>
    {% endif %}
</body>
</html>