code/kelin/labs/django_labs/lab01_todo/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    # path('', views.index, name='index'),
    path('todo/', views.todo, name='todo'),
    path('add/', views.add, name='add')
]

code/kelin/labs/django_labs/lab01_todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

code/kelin/labs/django_labs/lab05_blog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blogapp.urls')),
    path('admin/', admin.site.urls)
]

code/kelin/labs/django_labs/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

code/kelin/labs/django_labs/lab01_todo/myapp/models.py
# from django.db import models

# Create your models here.
from django.db import models

# class MyModel(models.Model):
#     myfield = models.CharField(max_length=200)
    
#     def __str__(self):
#         return self.myfield

class Priority(models.Model):
    # BOOL_CHOICES = [(1,'High'),(2,'Medium'),(3,'Low')]
    name = models.CharField(max_length=200) # Priority (high, medium, low) dropdown
    def __str__(self):
        return self.name

class ToDoItem(models.Model): 
    """
    Created Doc String
    """
    text = models.CharField(max_length=200) # ToDoItem text
    priority = models.ForeignKey(Priority, on_delete=models.CASCADE) # Foriegn Key to Priority
    created_date = models.DateTimeField(auto_now_add=True) # Created date

    def __str__(self):
        return self.text

        # return self.text, self.priority, self.created_date
        # return self.text, self.priority, self.created_date
        # return self.text, self.priority, self.created_date

code/kelin/labs/django_labs/lab01_todo/myapp/views.py
# from django.shortcuts import render

from django.urls import reverse
# Create your views here.

# from django.http import HttpResponse

# def myview(request):
#     return HttpResponse('hello world!')

from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Priority, ToDoItem

# from django.http import HttpResponse


# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

def todo(request):
    todo_items = ToDoItem.objects.all()
    # print("To do list", todo_items)
    context = {
        'todos_template': todo_items
    }
    return render(request, 'myapp/todo.html', context)

def add(request):
    # print("Keys", request.POST.keys())
    todo = request.POST['todo']
    priority = request.POST['priority']
    # print()
    # print(todo, priority)
    priority = Priority(name=priority)
    priority.save()
    todo = ToDoItem(text=todo, priority=priority)
    # print("Todo entry", todo)
    todo.save()
    return HttpResponseRedirect(reverse('myapp:todo'))

code/kelin/labs/django_labs/lab01_todo/myapp/templates/myapp/todo.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body><h4>Add Item</h4>
        <form action="{% url 'myapp:add' %}" method="post">
            {% csrf_token %}
            <label for="text">To Do:</label>
            <input id="todo" type="text" name="todo"/><br>
            <!-- Make dropdown menu for priority in template -->
            <label for="priority">Priority:</label>
            <select id="priority" name="priority">
            <option value="Low">Low</option>
            <option value="Medium">Medium</option>
            <option value="High">High</option>
            </select>
            <button type="submit">Add</button>
        </form>
<!-- {{ todos_template }} -->
        <ul><h3>To Do List</h3>
            {% for todo in todos_template %}
            <li>{{ todo.text }}</li>
            <li>Priority: {{ todo.priority }}</li>
            <li>Created: {{ todo.created_date }}</li>
            {% endfor %}
        </ul>
    </body>
</html>