code/daniel/js_files/daniel-pokedex/pokeapp/urls.py
from django.urls import path
from . import views

app_name = 'pokeapp'
urlpatterns = [
    path('', views.pokeview, name='pokeview'),
    path('pokemon/', views.pokemon, name='pokemon'),
    path('pokesearch/', views.pokesearch, name='search'),
]

code/daniel/js_files/daniel-pokedex/pokeproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pokeapp/', include('pokeapp.urls'))
    
]

code/daniel/js_files/daniel-pokedex/pokeapp/models.py
from django.db import models

class Pokemon(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    height = models.FloatField()
    weight = models.FloatField()
    image_front = models.CharField(max_length=200)
    image_back = models.CharField(max_length=200)
    # types = models.CharField(max_length=200)

code/daniel/js_files/daniel-pokedex/pokeapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, JsonResponse
from .models import Pokemon
from django.core import serializers
from django.db.models import Q
import json

def pokeview(request):
    myinstances = Pokemon.objects.all()
    context = {
        'myinstances': myinstances
    }
    return render(request, 'pokeapp/index.html', context)

def pokemon(request):
    listPokemon = Pokemon.objects.all()
    listResponse = serializers.serialize('json', listPokemon)

    return JsonResponse(listResponse, safe=False)

def pokesearch(request):
    search = request.POST.get("search") or ""
    print(search)
    
    if search:
        searchpoke = Pokemon.objects.filter(
            Q(name__icontains=search)
        
        )
    print(searchpoke)
    return render(request, 'pokeapp/index.html', { 'myinstance': searchpoke})
    

code/daniel/js_files/daniel-pokedex/pokeapp/templates/pokeapp/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
        <title></title>
        
    </head>
    <body>
        
        <form action="{% url 'pokeapp:search' %}" method="POST">
            
            <input type="text" placeholder="search pokemon" name="search">
            <button type="submit">go</button>
            {% csrf_token %}
        </form>

        <div id="app">
            {% for pokemon in myinstance %}
            <div>
                <ol>
                    <li>

                        number:{{ pokemon.number }}
                    </li>
                    <li>
                        name:{{ pokemon.name }}

                    </li>
                    <li>
                        weight:{{ pokemon.weight }}
                        
                    </li>
                    <li>
                        height:{{ pokemon.height }}

                    </li>
                    <li>
                        <img src="{{ pokemon.image_front }}">

                    </li>
                    <li>
                        <img src="{{ pokemon.image_back }}">

                    </li>
    

                </ol>

            </div>
            {% endfor %}
            <ol>
                <li v-for="poke in pokemon">${poke.fields.name}<br> <img :src="poke.fields.image_front"><img :src="poke.fields.image_back"></li>
            </ol>
            
        </div>
        <script>
            const app = new Vue({
                el: '#app',
                delimiters: ['${' , '}'],
                data: {
                    pokemon: [],
                    
                },
                methods: {
                    displayPokemon: function() {
                        axios({
                            method: 'get',
                            url: 'http://127.0.0.1:8000/pokeapp/pokemon/'
                         }).then((response) => {
                             this.pokemon = JSON.parse(response.data)
                            console.log(this.pokemon)
                            console.log(response.data)
                            })
                    }
            
                },
                created: function() {
                    this.displayPokemon()
            }
            
            }
            )
            
        </script>
    </body>
</html>

code/daniel/js_files/daniel-pokedex/pokeapp/templates/pokeapp/pokemontemplate.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script> <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script> <script src="{% static '/app.js' %}"></script> 
    </body>
</html>