code/Andy/django_lab/lab_05_blog/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog_app.urls')),
    path('users/', include('users.urls')),
]

code/Andy/django_lab/my_django_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

code/Andy/django_lab/todo_/newsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'))
]

code/Andy/django_lab/todo_/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('myview/' , views.index, name='index'),
    path('save/' , views.save, name='save') 
]

code/Andy/django_lab/todo/models.py
from django.db import models
from django.forms import CharField
from django.utils import timezone

class Priority(models.Model): 
    CHOICES = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High')
    )
    
    name = models.CharField(max_length = 200, choices = CHOICES, default ='low', null=True)

    def __str__(self) -> str:
        return f"{self.name}" #migrations only when you change or add a method
 


class Todoitem(models.Model):
    text = models.CharField(max_length =200, null=True)
    priority = models.ForeignKey(Priority, on_delete=models.CASCADE, null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True) #populates it right at the time added 

    def __str__(self) -> str:
        return f'{self.text} created at {self.created_date}'
    



# Create your models here.

code/Andy/django_lab/todo_/todo/models.py
from django.db import models
from django.forms import CharField
from django.utils import timezone

class Priority(models.Model): 
    CHOICES = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High')
    )
    
    name = models.CharField(max_length = 200, choices = CHOICES, default ='low', null=True)

    def __str__(self) -> str:
        return f"{self.name}" #migrations only when you change or add a method
 


class Todoitem(models.Model):
    text = models.CharField(max_length =200, null=True)
    priority = models.ForeignKey(Priority, on_delete=models.CASCADE, null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True) #populates it right at the time added 

    def __str__(self) -> str:
        return f'{self.text} created at {self.created_date}' 
    



# Create your models here.

code/Andy/django_lab/todo/views.py
from django.shortcuts import redirect, render   
from django.http import HttpResponse
from .models import Todoitem, Priority # to get both functions from models
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

# def myview(request):
#     return HttpResponse('hello world! Youre at the todo index.')

def index(request):
    todo_items = Todoitem.objects.all()
    # pri_item = Priority.objects.all()
    print('todo item', todo_items )
    print('type todo item', type(todo_items))

    context = {
        'todo_item': todo_items,
        # 'pri_item': pri_item
    } 

    return render(request, 'todo/index.html', context)


def save(request):
    form = request.POST
    # print(form)
    todo = form.get('text') #todo from html page. from user
    pri = form.get('name')
    # print(todo)
    # print(pri)
    p = Priority.objects.create(name=pri)
    Todoitem.objects.create(text=todo, priority=p)
    return redirect(reverse('todo:index'))

code/Andy/django_lab/todo_/todo/views.py
from django.shortcuts import redirect, render   
from django.http import HttpResponse
from .models import Todoitem, Priority # to get both functions from models
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

# def myview(request):
#     return HttpResponse('hello world! Youre at the todo index.')

def index(request):
    todo_items = Todoitem.objects.all()
    # pri_item = Priority.objects.all()
    # print('todo item', todo_items )
    # print('type todo item', type(todo_items))

    context = {
        'todo_item': todo_items,
        # 'pri_item': pri_item
    } 

    return render(request, 'todo/index.html', context)


def save(request):
    form = request.POST
    # print(form)
    todo = form.get('text') #todo from html page. from user
    pri = form.get('name')
    # print(todo)
    # print(pri)
    p = Priority.objects.create(name=pri)
    Todoitem.objects.create(text=todo, priority=p)
    return redirect(reverse('todo:index'))

code/Andy/django_lab/todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Document</title>
</head>
<body class="bg-dark text-light">
    <form action="{% url 'todo:save' %}"method='POST'> 
        <input name="text" id="text" placeholder="todo item">
        <input type="radio" id="low" name="name" value="low" >Low</input>
        <input type="radio" id="medium" name="name" value="medium" >Medium</input>
        <input type="radio" id="high" name="name" value="high" >High</input>
        <button type="submit">save</button>
        {% csrf_token %}
    </form>



    {% for item in todo_item %}
    <h1>{{item.text}}
        <p>{{item.created_date}}</p>
        <p>{{item.priority}}</p>
    </h1>

    
    {% endfor %}
    
</body>
</html>
<!-- line 10 the todo:save is from the view file todo is app and the save is the function written in the views app where we're trying to save the info   -->